'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2502
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2502.
'
Namespace WebReference
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebemsSoap", [Namespace]:="http://microsoft.com/")>  _
    Public Class Webems
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.68.6/WebService/Webems.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/Tra_Cuu_Ma_E1", RequestNamespace:="http://microsoft.com/", ResponseNamespace:="http://microsoft.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Tra_Cuu_Ma_E1(ByVal mae1 As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("Tra_Cuu_Ma_E1", New Object() {mae1})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginTra_Cuu_Ma_E1(ByVal mae1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Tra_Cuu_Ma_E1", New Object() {mae1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTra_Cuu_Ma_E1(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/TinhCuocEMSTrongNuoc", RequestNamespace:="http://microsoft.com/", ResponseNamespace:="http://microsoft.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TinhCuocEMSTrongNuoc(ByVal Ma_KH_E_Shipping As String, ByVal Buu_Cuc_Khai_Thac As Integer, ByVal Nuoc_Nhan As String, ByVal KHOI_LUONG As Integer, ByVal BC_NHAN As Integer, ByVal BC_TRA As Integer) As String
            Dim results() As Object = Me.Invoke("TinhCuocEMSTrongNuoc", New Object() {Ma_KH_E_Shipping, Buu_Cuc_Khai_Thac, Nuoc_Nhan, KHOI_LUONG, BC_NHAN, BC_TRA})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTinhCuocEMSTrongNuoc(ByVal Ma_KH_E_Shipping As String, ByVal Buu_Cuc_Khai_Thac As Integer, ByVal Nuoc_Nhan As String, ByVal KHOI_LUONG As Integer, ByVal BC_NHAN As Integer, ByVal BC_TRA As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TinhCuocEMSTrongNuoc", New Object() {Ma_KH_E_Shipping, Buu_Cuc_Khai_Thac, Nuoc_Nhan, KHOI_LUONG, BC_NHAN, BC_TRA}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTinhCuocEMSTrongNuoc(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/TinhCuocEMSQuocTe", RequestNamespace:="http://microsoft.com/", ResponseNamespace:="http://microsoft.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TinhCuocEMSQuocTe(ByVal Ma_KH_E_Shipping As String, ByVal Buu_Cuc_Khai_Thac As Integer, ByVal Nuoc_Nhan As String, ByVal LOAI_BP As Integer, ByVal KHOI_LUONG As Integer, ByVal NUOC_PHAT As String) As String
            Dim results() As Object = Me.Invoke("TinhCuocEMSQuocTe", New Object() {Ma_KH_E_Shipping, Buu_Cuc_Khai_Thac, Nuoc_Nhan, LOAI_BP, KHOI_LUONG, NUOC_PHAT})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTinhCuocEMSQuocTe(ByVal Ma_KH_E_Shipping As String, ByVal Buu_Cuc_Khai_Thac As Integer, ByVal Nuoc_Nhan As String, ByVal LOAI_BP As Integer, ByVal KHOI_LUONG As Integer, ByVal NUOC_PHAT As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TinhCuocEMSQuocTe", New Object() {Ma_KH_E_Shipping, Buu_Cuc_Khai_Thac, Nuoc_Nhan, LOAI_BP, KHOI_LUONG, NUOC_PHAT}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTinhCuocEMSQuocTe(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
