'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace USPS_E1MAP
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="KHLSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class KHL
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ems.com.vn/portal/KHL/KHL.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAndTrace_KHL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackAndTrace_KHL(ByVal CustomerCode As String, ByVal FromDate As String, ByVal ToDate As String) As TrackAndTrace_KHLResponseTrackAndTrace_KHLResult
            Dim results() As Object = Me.Invoke("TrackAndTrace_KHL", New Object() {CustomerCode, FromDate, ToDate})
            Return CType(results(0),TrackAndTrace_KHLResponseTrackAndTrace_KHLResult)
        End Function
        
        '<remarks/>
        Public Function BeginTrackAndTrace_KHL(ByVal CustomerCode As String, ByVal FromDate As String, ByVal ToDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackAndTrace_KHL", New Object() {CustomerCode, FromDate, ToDate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackAndTrace_KHL(ByVal asyncResult As System.IAsyncResult) As TrackAndTrace_KHLResponseTrackAndTrace_KHLResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TrackAndTrace_KHLResponseTrackAndTrace_KHLResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAndTrace_item", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackAndTrace_item(ByVal ItemCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TrackAndTrace_item", New Object() {ItemCode})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginTrackAndTrace_item(ByVal ItemCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackAndTrace_item", New Object() {ItemCode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackAndTrace_item(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAndTrace_Batch", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackAndTrace_Batch(ByVal BatchCodeString As String) As TrackAndTrace_BatchResponseTrackAndTrace_BatchResult
            Dim results() As Object = Me.Invoke("TrackAndTrace_Batch", New Object() {BatchCodeString})
            Return CType(results(0),TrackAndTrace_BatchResponseTrackAndTrace_BatchResult)
        End Function
        
        '<remarks/>
        Public Function BeginTrackAndTrace_Batch(ByVal BatchCodeString As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackAndTrace_Batch", New Object() {BatchCodeString}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackAndTrace_Batch(ByVal asyncResult As System.IAsyncResult) As TrackAndTrace_BatchResponseTrackAndTrace_BatchResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TrackAndTrace_BatchResponseTrackAndTrace_BatchResult)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAndTrace_KHL_Test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackAndTrace_KHL_Test(ByVal CustomerCode As String, ByVal Province As String, ByVal FromDate As String, ByVal ToDate As String) As String
            Dim results() As Object = Me.Invoke("TrackAndTrace_KHL_Test", New Object() {CustomerCode, Province, FromDate, ToDate})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTrackAndTrace_KHL_Test(ByVal CustomerCode As String, ByVal Province As String, ByVal FromDate As String, ByVal ToDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackAndTrace_KHL_Test", New Object() {CustomerCode, Province, FromDate, ToDate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackAndTrace_KHL_Test(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackAndTrace_item_PH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackAndTrace_item_PH(ByVal ItemCode As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TrackAndTrace_item_PH", New Object() {ItemCode})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginTrackAndTrace_item_PH(ByVal ItemCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackAndTrace_item_PH", New Object() {ItemCode}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackAndTrace_item_PH(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrackTrace_Items_Arr", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrackTrace_Items_Arr(ByVal Mae1_Arr As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("TrackTrace_Items_Arr", New Object() {Mae1_Arr})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginTrackTrace_Items_Arr(ByVal Mae1_Arr As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrackTrace_Items_Arr", New Object() {Mae1_Arr}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTrackTrace_Items_Arr(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/E1_USPS_Cap_Nhat_Them", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function E1_USPS_Cap_Nhat_Them(ByVal MaE1 As String, ByVal MaUSPS As String, ByVal Status As Integer) As String
            Dim results() As Object = Me.Invoke("E1_USPS_Cap_Nhat_Them", New Object() {MaE1, MaUSPS, Status})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginE1_USPS_Cap_Nhat_Them(ByVal MaE1 As String, ByVal MaUSPS As String, ByVal Status As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("E1_USPS_Cap_Nhat_Them", New Object() {MaE1, MaUSPS, Status}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndE1_USPS_Cap_Nhat_Them(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class TrackAndTrace_KHLResponseTrackAndTrace_KHLResult
        
        '<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Any() As System.Xml.XmlElement
        
        '<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Any1 As System.Xml.XmlElement
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Class TrackAndTrace_BatchResponseTrackAndTrace_BatchResult
        
        '<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Any() As System.Xml.XmlElement
        
        '<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Any1 As System.Xml.XmlElement
    End Class
End Namespace
