'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace E1_USPS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="E1_MAPSoap", [Namespace]:="http://tempuri.org/")>  _
    Public Class E1_MAP
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ems.com.vn/portal/e1map/e1_map.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/E1_USPS_Cap_Nhat_Them", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function E1_USPS_Cap_Nhat_Them(ByVal MaE1 As String, ByVal MaUSPS As String, ByVal Status As Integer) As String
            Dim results() As Object = Me.Invoke("E1_USPS_Cap_Nhat_Them", New Object() {MaE1, MaUSPS, Status})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginE1_USPS_Cap_Nhat_Them(ByVal MaE1 As String, ByVal MaUSPS As String, ByVal Status As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("E1_USPS_Cap_Nhat_Them", New Object() {MaE1, MaUSPS, Status}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndE1_USPS_Cap_Nhat_Them(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
